import test from 'node:test';
import assert from 'node:assert/strict';
import {cpSync,mkdirSync,mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {prepareContent,root} from './prepare-content.mjs';
import {readMarkdownContent} from './markdown-content.mjs';
function fixture(fn){const dir=mkdtempSync(join(tmpdir(),'precip-markdown-'));try{mkdirSync(join(dir,'metadata'));cpSync(join(root,'metadata/datasets-and-guidance'),join(dir,'metadata/datasets-and-guidance'),{recursive:true,dereference:true,filter:p=>!p.includes('/.git')});mkdirSync(join(dir,'scripts'));cpSync(join(root,'scripts/content-schema.json'),join(dir,'scripts/content-schema.json'));fn(dir);}finally{rmSync(dir,{recursive:true,force:true});}}
test('Markdown and figures assemble together',()=>fixture(dir=>{prepareContent(dir);assert.ok(JSON.parse(readFileSync(join(dir,'content/schema.json'))).definitions.product);assert.ok(readFileSync(join(dir,'public/content-assets/guidance/figures/annual-maximum.png')).length>0);const sources=JSON.parse(readFileSync(join(dir,'content/source-map.json')));assert.equal(sources['product-guidance/loca2.md'],'datasets/loca2.nt');}));
test('missing source reports setup command',()=>{const dir=mkdtempSync(join(tmpdir(),'precip-empty-'));try{assert.throws(()=>prepareContent(dir),/git submodule update --init --recursive/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('invalid edit preserves the last assembled content',()=>fixture(dir=>{prepareContent(dir);const before=readFileSync(join(dir,'content/products/loca2.yaml'),'utf8');const file=join(dir,'metadata/datasets-and-guidance/datasets/loca2.nt');writeFileSync(file,readFileSync(file,'utf8').replace('model count: 27','model count: many'));assert.throws(()=>prepareContent(dir),/loca2.nt:.*expected a number/);assert.equal(readFileSync(join(dir,'content/products/loca2.yaml'),'utf8'),before);}));
test('a dataset added to INDEX.md needs no conversion-code changes',()=>fixture(dir=>{const src=join(dir,'metadata/datasets-and-guidance');const text=readFileSync(join(src,'datasets/loca2.nt'),'utf8').replaceAll('loca2','new-example');writeFileSync(join(src,'datasets/new-example.nt'),text);const index=join(src,'INDEX.md');writeFileSync(index,readFileSync(index,'utf8').replace('## Datasets','## Datasets\n\n- [New example](datasets/new-example.nt)'));assert.equal(readMarkdownContent(src).get('products/new-example.yaml').value.id,'new-example');}));
test('regional output cannot overwrite a dataset guidance document',()=>fixture(dir=>{const source=join(dir,'metadata/datasets-and-guidance');cpSync(join(source,'templates/regional-dataset.nt'),join(source,'datasets/regional/loca2.nt'));assert.throws(()=>prepareContent(dir),/Duplicate generated path product-guidance\/loca2.md/);}));
test('editing the shared BibTeX file updates assembled references',()=>fixture(dir=>{const file=join(dir,'metadata/datasets-and-guidance/references.bib');const text=readFileSync(file,'utf8');writeFileSync(file,text.replace('Future Increases in North American Extreme Precipitation in CMIP6 Downscaled with LOCA','Updated reference title'));prepareContent(dir);assert.match(readFileSync(join(dir,'content/papers.yaml'),'utf8'),/Updated reference title/);}));
test('reviewer lists can be added without changing the site field layout',()=>fixture(dir=>{const file=join(dir,'metadata/datasets-and-guidance/datasets/loca2.nt');const text=readFileSync(file,'utf8').replace('status: draft','status: expert-reviewed\n    reviewed by:\n      - Example Expert\n    reviewed on: 2026-09-11');writeFileSync(file,text);const r=readMarkdownContent(join(dir,'metadata/datasets-and-guidance')).get('products/loca2.yaml');assert.deepEqual(r.value.expert_guidance.review.reviewed_by,['Example Expert']);}));
test('unlisted datasets and dangling index links fail before replacing assembled content',()=>fixture(dir=>{const source=join(dir,'metadata/datasets-and-guidance');cpSync(join(source,'datasets/loca2.nt'),join(source,'datasets/unlisted.nt'));assert.throws(()=>prepareContent(dir),/missing entry in INDEX.md/);rmSync(join(source,'datasets/unlisted.nt'));rmSync(join(source,'datasets/loca2.nt'));assert.throws(()=>prepareContent(dir),/loca2.nt/);}));
