import test from 'node:test';
import assert from 'node:assert/strict';
import {cpSync,mkdirSync,mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {prepareContent,root} from './prepare-content.mjs';
import {parseMarkdown,readMarkdownContent} from './markdown-content.mjs';
function fixture(fn){const dir=mkdtempSync(join(tmpdir(),'precip-markdown-'));try{mkdirSync(join(dir,'metadata'));cpSync(join(root,'metadata/datasets-and-guidance'),join(dir,'metadata/datasets-and-guidance'),{recursive:true,dereference:true,filter:p=>!p.includes('/.git')});mkdirSync(join(dir,'scripts'));cpSync(join(root,'scripts/content-schema.json'),join(dir,'scripts/content-schema.json'));fn(dir);}finally{rmSync(dir,{recursive:true,force:true});}}
test('Markdown and figures assemble together',()=>fixture(dir=>{prepareContent(dir);assert.ok(JSON.parse(readFileSync(join(dir,'content/schema.json'))).definitions.product);assert.ok(readFileSync(join(dir,'public/content-assets/guidance/figures/annual-maximum.png')).length>0);const sources=JSON.parse(readFileSync(join(dir,'content/source-map.json')));assert.equal(sources['product-guidance/loca2.md'],'datasets/loca2.md');}));
test('missing source reports setup command',()=>{const dir=mkdtempSync(join(tmpdir(),'precip-empty-'));try{assert.throws(()=>prepareContent(dir),/git submodule update --init --recursive/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('invalid edit preserves the last assembled content',()=>fixture(dir=>{prepareContent(dir);const before=readFileSync(join(dir,'content/products/loca2.yaml'),'utf8');const file=join(dir,'metadata/datasets-and-guidance/datasets/loca2.md');writeFileSync(file,readFileSync(file,'utf8').replace('| Model Count | 27 |','| Model Count | many |'));assert.throws(()=>prepareContent(dir),/loca2.md: Expected a number/);assert.equal(readFileSync(join(dir,'content/products/loca2.yaml'),'utf8'),before);}));
test('new dataset Markdown is discovered without changing conversion code',()=>fixture(dir=>{const src=join(dir,'metadata/datasets-and-guidance');const text=readFileSync(join(src,'datasets/loca2.md'),'utf8').replaceAll('loca2','new-example');writeFileSync(join(src,'datasets/new-example.md'),text);assert.equal(readMarkdownContent(src).get('products/new-example.yaml').value.id,'new-example');}));
test('prose, equations and escaped table bars survive conversion',()=>{const text='# Example\n\n| Field | Value |\n| --- | --- |\n| Name | a\\|b |\n| Count | 2 |\n\n## Guidance\n\nFree **prose** and $x^2$.\n';const parsed=parseMarkdown(text,{name:'string',count:'number'});assert.deepEqual(parsed.value,{name:'a|b',count:2});assert.equal(parsed.body,'\nFree **prose** and $x^2$.\n');});
test('duplicate fields and unknown sections fail with a filename',()=>{assert.throws(()=>parseMarkdown('# A\n\n| Field | Value |\n| --- | --- |\n| Name | A |\n| Name | B |\n',{name:'string'},'example.md'),/example.md: Duplicate field/);assert.throws(()=>parseMarkdown('# A\n\n## Typo\n\nNo entries.\n',{},'example.md'),/example.md: Unknown section/);});
test('Windows line endings preserve guidance',()=>{const parsed=parseMarkdown('# Example\r\n\r\n| Field | Value |\r\n| --- | --- |\r\n| Name | Rain |\r\n\r\n## Guidance\r\n\r\nAdvice.\r\n',{name:'string'});assert.equal(parsed.body,'\nAdvice.\n');});
test('an unescaped table bar fails instead of discarding content',()=>assert.throws(()=>parseMarkdown('# Example\n\n| Field | Value |\n| --- | --- |\n| Name | rain | lost |\n',{name:'string'}),/different number of cells/));
test('regional output cannot overwrite a dataset guidance document',()=>fixture(dir=>{const source=join(dir,'metadata/datasets-and-guidance');cpSync(join(source,'templates/regional-guidance.md'),join(source,'datasets/regional/loca2.md'));assert.throws(()=>prepareContent(dir),/Duplicate generated path product-guidance\/loca2.md/);}));
test('editing the shared BibTeX file updates assembled references',()=>fixture(dir=>{const file=join(dir,'metadata/datasets-and-guidance/references.bib');const text=readFileSync(file,'utf8');writeFileSync(file,text.replace('Future Increases in North American Extreme Precipitation in CMIP6 Downscaled with LOCA','Updated reference title'));prepareContent(dir);assert.match(readFileSync(join(dir,'content/papers.yaml'),'utf8'),/Updated reference title/);}));
